modLoader="javafml" 
loaderVersion="[2,)"
issueTrackerURL="https://github.com/LootrMinecraft/Lootrmentaries/issues"
license="https://github.com/LootrMinecraft/Lootrmentaries/blob/arch-1.21/LICENSE"
[[mods]]
    modId="lootrmentaries"
    version="${version}"
    displayName="Lootr & Supplementaries Compatibility"
    displayURL="https://minecraft.curseforge.com/projects/lootrmentaries"
    authors="Noobanidus"
    description="Adding native safe, urn, etc compatibility to Supplementaries & Lootr."

[[dependencies.lootrmentaries]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"

[[dependencies.lootrmentaries]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"

[[dependencies.lootrmentaries]]
    modId="lootr"
    type="required"
    versionRange="[1.21-1.10.35.97,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.lootrmentaries]]
    modId="supplementaries"
    type="required"
    versionRange="[1.7.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config="lootrmentaries-common.mixins.json"